CREATE DATABASE IF NOT EXISTS manicure;

CREATE TABLE IF DOES NOT EXISTS CLIENTES(
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (80)  NOT NULL,
TELEFONE CHAR (11) UNIQUE NOT NULL,
EMAIL VARCHAR (50) UNIQUE,
SERVICO VARCHAR (50) NOT NULL,
PRECO_SERVICO DOUBLE NOT NULL
)

